### ISSUE TITLE
ReplitのDenoテンプレートの`.deno`ディレクトリがコミットされている

### ISSUE THREAD

**Issue by nakasyou** [EdamAme-x/nozoki#1]
ReplitのDenoテンプレートの`.deno`ディレクトリがコミットされています。
`.gitignore`に`/.deno/`を追加することを推奨します。

**Comment by EdamAme-x** [comment]
replit初心者で `.deno` の意味がよくわかっとらんやが
見た感じキャッシュ (Deno版 node_modulesなのかな)
了解
